### ISSUE TITLE
Assets

### ISSUE THREAD

**Issue by hyochan** [hyochan/expo-iap#5]
<img src="https://github.com/user-attachments/assets/f51a4b1b-b257-47bf-afe7-5ef8692f0594" height="200"/>

**Comment by hyochan** [comment]
![Image](https://github.com/user-attachments/assets/ad8d830b-30ff-48ab-8661-a688f53536e1)

**Comment by hyochan** [comment]
Hey @SethArchambault 

Thank you so much for taking the time to share your perspective — I really appreciate it. I'm truly sorry you're going through such an intense and painful situation. What you described is horrifying, and I completely understand how the image could feel out of place or even hurtful in that context.

Just a quick note — the image was meant as a light parody of the “Make X Great Again” meme format, definitely not to trivialize anything serious or ignore the very real suffering happening around us. I really appreciate your honesty and the reminder that humor can land very differently depending on what people are experiencing.

I'll keep the image up for now just so the context of the conversation stays clear, but I plan to replace it soon with something more neutral. I’ll be more thoughtful going forward, and I’m grateful you called this out.

Wishing you strength and safety — and thank you again.

**Comment by SethArchambault** [comment]
Thanks! Appreciate you being open to this feedback.. I feel like it's rare to have a conversation online that ends in deeper understanding - I know you didn't have a bad intent when you went about creating this art, and I appreciate all the work you've put into this project. Thanks for the well wishes - I wish the same to you!

(Just a heads up: I willl delete this message and my other message shortly - it's a more vulnerable conversation that I normally have attached to my public github account)

**Comment by hyochan** [comment]
@SethArchambault I’ve just redesigned and replaced the logo. I hope this brings you even a little comfort. Thank you.

**Comment by SethArchambault** [comment]
Nice! Looking forward to adopting this - appreciate you! ☺️
